import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#f7f8fa' },
  appShell: { flex: 1, backgroundColor: '#f7f8fa' },
  content: { paddingHorizontal: 24, paddingTop: 56, paddingBottom: 114 },
  authShell: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 70,
    paddingBottom: 34,
    justifyContent: 'center',
    gap: 24,
  },
  authHeader: { gap: 10 },
  authBrand: { color: '#05a780', fontSize: 17, fontWeight: '900', textTransform: 'uppercase' },
  authTitle: { color: '#111111', fontSize: 42, lineHeight: 48, fontWeight: '900', letterSpacing: 0 },
  authCopy: { color: '#5c6268', fontSize: 17, lineHeight: 24, fontWeight: '700' },
  authCard: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    borderWidth: 2,
    borderColor: '#dfe3e6',
    padding: 18,
    gap: 14,
  },
  authModeRow: { flexDirection: 'row', backgroundColor: '#edf2f4', borderRadius: 16, padding: 4, gap: 4 },
  authModeButton: { flex: 1, minHeight: 42, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  authModeButtonActive: { backgroundColor: '#101820' },
  authModeText: { color: '#6a737d', fontSize: 14, fontWeight: '900' },
  authModeTextActive: { color: '#ffffff' },
  authInputWrap: { gap: 7 },
  authDepartmentGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  authDepartmentChip: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d7dee4',
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: '#f8fafb',
  },
  authDepartmentChipActive: { borderColor: '#05b58d', backgroundColor: '#e4f8f3' },
  authDepartmentText: { color: '#5c6268', fontSize: 13, fontWeight: '900' },
  authDepartmentTextActive: { color: '#00765b' },
  authSubmitButton: {
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: '#050505',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  authSubmitText: { color: '#ffffff', fontWeight: '900', fontSize: 16 },
  authErrorText: { color: '#d0273c', fontSize: 13, fontWeight: '800', lineHeight: 18 },
  syncMessage: { color: '#00765b', fontSize: 13, fontWeight: '900', lineHeight: 18 },
  settingsBack: { color: '#00765b', fontSize: 17, fontWeight: '900' },
  settingsCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#dfe3e6',
    padding: 16,
    gap: 12,
  },
  settingsCardTitle: { color: '#111111', fontSize: 20, fontWeight: '900' },
  settingsText: { color: '#5c6268', fontSize: 14, lineHeight: 20, fontWeight: '700' },
  settingsRow: {
    minHeight: 82,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#dfe3e6',
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  settingsRowTitle: { color: '#111111', fontSize: 18, fontWeight: '900' },
  settingsRowMeta: { color: '#5c6268', fontSize: 13, fontWeight: '700', marginTop: 4 },
  settingsChevron: { color: '#111111', fontSize: 34, fontWeight: '700' },
  goalInputRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  goalInput: { flex: 1 },
  goalSaveButton: {
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: '#050505',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  goalSaveText: { color: '#ffffff', fontWeight: '900', fontSize: 14 },
  signOutButton: {
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: '#ffe2e2',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#ffb8b8',
  },
  signOutText: { color: '#c81e35', fontWeight: '900', fontSize: 15 },
  screen: { gap: 16 },
  topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  topStats: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', gap: 18 },
  profileButton: {
    width: 42,
    height: 42,
    borderRadius: 16,
    backgroundColor: '#101820',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileButtonText: { color: '#ffffff', fontSize: 18, fontWeight: '900' },
  pill: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  pillIcon: { fontSize: 25, fontWeight: '900' },
  blueIcon: { color: '#149af3' },
  flameIcon: { color: '#ff3d5c' },
  pillValue: { color: '#0c0d0f', fontSize: 18, fontWeight: '900' },
  pillCaption: { color: '#6a737d', fontSize: 10, fontWeight: '900', marginTop: -2 },
  calendarButton: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },
  calendarIcon: { color: '#0c0d0f', fontSize: 21, fontWeight: '900' },
  dateBlock: { marginTop: 6 },
  focusCard: { backgroundColor: '#101820', borderRadius: 22, padding: 18, gap: 12 },
  focusLabel: { color: '#54d6b3', fontSize: 13, fontWeight: '900', textTransform: 'uppercase' },
  focusText: { color: '#ffffff', fontSize: 17, lineHeight: 23, fontWeight: '800' },
  profilePanel: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    borderWidth: 2,
    borderColor: '#dfe3e6',
    padding: 16,
    gap: 14,
  },
  profilePanelTitle: { color: '#111111', fontSize: 20, fontWeight: '900' },
  profilePanelText: { color: '#5c6268', fontSize: 14, lineHeight: 20, fontWeight: '700', marginTop: 4 },
  departmentGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  departmentChip: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#31414c',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#18242d',
  },
  departmentChipActive: { borderColor: '#54d6b3', backgroundColor: '#dffaf3' },
  departmentChipText: { color: '#b8c4cc', fontSize: 13, fontWeight: '900' },
  departmentChipTextActive: { color: '#00765b' },
  calendarPanel: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    borderWidth: 2,
    borderColor: '#dfe3e6',
    padding: 16,
    gap: 14,
  },
  calendarPanelHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  calendarTitle: { color: '#111111', fontSize: 20, fontWeight: '900' },
  calendarHint: { color: '#00765b', fontSize: 13, fontWeight: '900' },
  calendarGrid: { flexDirection: 'row', justifyContent: 'space-between', gap: 6 },
  calendarDay: { flex: 1, alignItems: 'center', gap: 7 },
  calendarBubble: {
    width: 42,
    height: 42,
    borderRadius: 16,
    backgroundColor: '#dfe5e8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarBubbleDone: { backgroundColor: '#05b58d' },
  calendarBubbleText: { color: '#111111', fontSize: 12, fontWeight: '900' },
  calendarBubbleTextDone: { color: '#ffffff' },
  calendarDayLabel: { color: '#6a737d', fontSize: 11, fontWeight: '900' },
  calendarFootnote: { color: '#6a737d', fontSize: 12, fontWeight: '700' },
  pageTitleBlock: { marginBottom: 2 },
  todayTitle: { color: '#111111', fontSize: 42, lineHeight: 48, fontWeight: '900', letterSpacing: 0 },
  weekText: { color: '#171717', fontSize: 21, fontWeight: '600', marginTop: 8, lineHeight: 27 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 10 },
  sectionTitleLarge: { color: '#111111', fontSize: 27, fontWeight: '900', letterSpacing: 0 },
  detailsLink: { color: '#00765b', fontSize: 18, fontWeight: '900' },
  summaryCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#dfe3e6',
    paddingHorizontal: 20,
    paddingVertical: 24,
    gap: 22,
  },
  summaryTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  summaryMetric: { width: 78, alignItems: 'center' },
  summaryMetricValue: { color: '#111111', fontSize: 23, fontWeight: '900' },
  summaryMetricLabel: { color: '#5c6268', fontSize: 16, fontWeight: '600', marginTop: 3 },
  ringWrap: { width: 150, height: 150, alignItems: 'center', justifyContent: 'center' },
  ringTrack: {
    width: 136,
    height: 136,
    borderRadius: 68,
    borderWidth: 10,
    borderColor: '#e1e5e8',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  ringFill: {
    position: 'absolute',
    width: 136,
    height: 136,
    borderRadius: 68,
    borderWidth: 10,
    borderLeftColor: '#05b58d',
    borderTopColor: '#05b58d',
    borderRightColor: 'transparent',
    borderBottomColor: 'transparent',
  },
  ringCenter: {
    width: 108,
    height: 108,
    borderRadius: 54,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  remainingValue: { color: '#111111', fontSize: 31, fontWeight: '900' },
  remainingLabel: { color: '#5c6268', fontSize: 16, fontWeight: '600' },
  subjectBars: { flexDirection: 'row', justifyContent: 'space-between', gap: 16 },
  subjectBarItem: { flex: 1, alignItems: 'center', gap: 8 },
  subjectBarLabel: { color: '#5c6268', fontSize: 16, fontWeight: '700' },
  subjectTrack: { width: '100%', height: 10, borderRadius: 5, backgroundColor: '#dfe5e8', overflow: 'hidden' },
  subjectFill: { height: '100%', borderRadius: 5, backgroundColor: '#05b58d' },
  subjectAmount: { color: '#111111', fontSize: 13, fontWeight: '900' },
  detailGrid: { flexDirection: 'row', gap: 10 },
  miniDetail: { flex: 1, backgroundColor: '#f3f6f8', borderRadius: 14, padding: 12, alignItems: 'center' },
  miniDetailValue: { color: '#111111', fontSize: 17, fontWeight: '900', maxWidth: '100%' },
  miniDetailLabel: { color: '#5c6268', fontSize: 12, fontWeight: '800', marginTop: 4 },
  blockList: { backgroundColor: '#ffffff', borderRadius: 20, borderWidth: 2, borderColor: '#dfe3e6', overflow: 'hidden' },
  studyBlock: {
    minHeight: 126,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    borderBottomWidth: 2,
    borderColor: '#e5e8eb',
    gap: 14,
  },
  blockRing: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 8,
    borderColor: '#05b58d',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#eefaf7',
  },
  blockIcon: { color: '#111111', fontSize: 24, fontWeight: '900' },
  studyBlockBody: { flex: 1, minWidth: 0 },
  blockTitle: { color: '#111111', fontSize: 20, fontWeight: '900' },
  blockMeta: { color: '#5c6268', fontSize: 17, fontWeight: '600', marginTop: 5 },
  aiTagRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 7 },
  aiTag: {
    backgroundColor: '#ead8ff',
    color: '#5f31d1',
    borderRadius: 8,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 3,
    fontSize: 13,
    fontWeight: '900',
  },
  blockTopic: { flex: 1, color: '#5c6268', fontSize: 15, fontWeight: '600' },
  addCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#050505',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addCircleText: { color: '#ffffff', fontSize: 34, lineHeight: 36, fontWeight: '700' },
  formCard: {
    borderRadius: 20,
    backgroundColor: '#ffffff',
    padding: 18,
    borderWidth: 2,
    borderColor: '#dfe3e6',
    gap: 14,
  },
  cardTitle: { color: '#111111', fontSize: 21, fontWeight: '900' },
  inputRow: { flexDirection: 'row', gap: 10 },
  inputWrap: { flex: 1, gap: 7 },
  inputLabel: { color: '#5c6268', fontSize: 14, fontWeight: '900' },
  input: {
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d7dee4',
    paddingHorizontal: 13,
    color: '#111111',
    backgroundColor: '#f8fafb',
    fontWeight: '800',
  },
  selectorWrap: { gap: 8 },
  chipList: { gap: 8, paddingRight: 4 },
  chip: {
    minHeight: 42,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d7dee4',
    backgroundColor: '#f8fafb',
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipActive: { borderColor: '#05b58d', backgroundColor: '#e4f8f3' },
  chipText: { color: '#5c6268', fontSize: 14, fontWeight: '900' },
  chipTextActive: { color: '#00765b' },
  primaryButton: {
    minHeight: 50,
    borderRadius: 16,
    backgroundColor: '#050505',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  primaryButtonText: { color: '#ffffff', fontWeight: '900', fontSize: 15 },
  secondaryButton: {
    minHeight: 50,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#97e8d4',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 18,
  },
  secondaryButtonText: { color: '#dffdf5', fontWeight: '900', fontSize: 15 },
  analysisCard: { borderRadius: 20, backgroundColor: '#ffffff', padding: 18, borderWidth: 2, borderColor: '#dfe3e6' },
  analysisText: { color: '#5c6268', fontWeight: '700', fontSize: 16, lineHeight: 23, marginTop: 8 },
  progressWrap: { borderRadius: 18, backgroundColor: '#ffffff', padding: 16, borderWidth: 2, borderColor: '#dfe3e6' },
  progressHeader: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  progressLabel: { flex: 1, color: '#111111', fontWeight: '900' },
  progressValue: { color: '#00765b', fontWeight: '900' },
  progressTrack: { height: 10, borderRadius: 5, backgroundColor: '#dfe5e8', marginTop: 10, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 5, backgroundColor: '#05b58d' },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 18,
    backgroundColor: '#ffffff',
    padding: 16,
    borderWidth: 2,
    borderColor: '#dfe3e6',
  },
  activityDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#05b58d', marginRight: 12 },
  activityBody: { flex: 1 },
  activityTitle: { color: '#111111', fontSize: 16, fontWeight: '900' },
  activityMeta: { color: '#5c6268', marginTop: 4, fontSize: 13, fontWeight: '700' },
  aiPanel: { borderRadius: 20, backgroundColor: '#111111', padding: 22 },
  aiMark: {
    width: 48,
    height: 30,
    borderRadius: 10,
    backgroundColor: '#ead8ff',
    color: '#5f31d1',
    textAlign: 'center',
    textAlignVertical: 'center',
    fontWeight: '900',
    overflow: 'hidden',
    marginBottom: 14,
  },
  aiTitle: { color: '#ffffff', fontSize: 25, lineHeight: 31, letterSpacing: 0, fontWeight: '900' },
  aiCopy: { color: '#cdd3d8', fontSize: 15, lineHeight: 22, marginTop: 10, fontWeight: '700' },
  tabBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    minHeight: 86,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-around',
    paddingHorizontal: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderColor: '#e2e6ea',
  },
  tabButton: { width: 62, alignItems: 'center', justifyContent: 'center', gap: 4 },
  tabIconWrap: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center' },
  tabIconWrapActive: { borderBottomWidth: 3, borderColor: '#05b58d' },
  tabIcon: { color: '#969ca2', fontSize: 21, fontWeight: '900' },
  tabIconActive: { color: '#05a780' },
  tabLabel: { color: '#969ca2', fontSize: 12, fontWeight: '900' },
  tabLabelActive: { color: '#00765b' },
});
